### PR TITLE
made functionality works on pressing enter key

### PR DESCRIPTION
**Pull request by 777Prabhjot**
hey, hope you are doing well i have solved the issue but it's not working on color picker all the other inputs are working fine please do check it out thank you.

### CODE REVIEW

**Comment by TheCoderAdi** [comment]
Hello @777Prabhjot , 
I will check the PR after the coding period start for hackodex. 
Thanks for the intrest.

**Comment by TheCoderAdi** [comment]
hello @777Prabhjot ,
Have you register for hackodex2023 , if not then register first otherwise your PRs will be not tracked.
go to this site :- https://hackodex.codex-iter.in/
Give a thumbs up if you are already done..

**Comment by TheCoderAdi** [comment]
> hello @777Prabhjot , Have you register for hackodex2023 , if not then register first otherwise your PRs will not be tracked. go to this site :- https://hackodex.codex-iter.in/ Give a thumbs up if you are already done..

**Comment by 777Prabhjot** [comment]
@TheCoderAdi just done now

**Comment by TheCoderAdi** [comment]
Hello , Fix this issue @777Prabhjot 
Screenshot 2023-04-10 180918
I think you have added a form , so that it is behaving like this try to change the codes and also prevent empty value to be entered

**Comment by TheCoderAdi** [comment]
I have merged your PR ,
Congratulations..

**Pull request merged**
