### PR TITLE
Add a new game

### PR DESCRIPTION
**Pull request by harsh0853**
I have added a new SpaceShooter Game. In the index.html I have added a new button for the game in the navigation bar.

### CODE REVIEW

**Comment by TheCoderAdi** [comment]
First pull the previous commit of the repo and then add your game file

**Comment by harsh0853** [comment]
> First pull the previous commit of the repo and then add your game file

hey, actually i'm a beginner.. so can you plse help me how can i do the above mentioned task ?

**Comment by TheCoderAdi** [comment]
> > First pull the previous commit of the repo and then add your game file
> 
> hey, actually i'm a beginner.. so can you plse help me how can i do the above mentioned task ?

Okay
p

> > First pull the previous commit of the repo and then add your game file
> 
> hey, actually i'm a beginner.. so can you plse help me how can i do the above mentioned task ?

Okay 
Open your project directory in which you clone the repo , open terminal there and run the below command
git pull https://github.com/TheCoderAdi/GamingBeast.git
after this command your branch will up to date and move your html file into the html folder. 
After this make a pull request.
If any problem , then reply me..

**Comment by harsh0853** [comment]
Check if it is okay..

**Comment by TheCoderAdi** [comment]
Move SecondGame.html file to games_file and SecondGameStyle.css to css_file and link them with index.html

**Comment by harsh0853** [comment]
Please check the latest one if it is okay..

**Comment by TheCoderAdi** [comment]
Merged

**Pull request merged**
